workflows:
  build-app:
    name: Build Android App
    instance_type: linux
    max_build_duration: 10
    environment:
      vars:
        FLUTTER_CHANNEL: stable
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
